runtime: python37

handlers:
- url: /(.+\.js)$
  static_files: \1
  upload: (.+\.js)$
  mime_type: application/javascript

- url: /(.+\.css)$
  static_files: \1
  upload: (.+\.css)$
  mime_type: text/css

- url: /(.+\.html)$
  static_files: \1
  upload: (.+\.html)$
  mime_type: text/html

- url: /
  static_files: index.html
  upload: index.html
  mime_type: text/html
